export function getPanelContent(): string {
  return [
    '  <div id="warn-bar"></div>',
    '  <div id="hdr">',
    '    <div class="logo">Terminal Buddy</div>',
    '    <div id="ai-badge">Waiting...</div>',
    '  </div>',
    '  <div id="pet">',
    '    <div id="pet-emoji">🥚</div>',
    '    <div id="pet-info">',
    '      <div id="pet-row">',
    '        <div id="pet-name">Buddy</div>',
    '        <div id="pet-lv">Lv.1</div>',
    '      </div>',
    '      <div id="pet-mood">Hatching...</div>',
    '      <div id="xp-track"><div id="xp-fill"></div></div>',
    '    </div>',
    '  </div>',
    '  <div id="stats-bar">',
    '    <div class="st-item" id="st-ok"><span class="st-val">0</span><span class="st-label">Success</span></div>',
    '    <div class="st-item" id="st-err"><span class="st-val">0</span><span class="st-label">Errors</span></div>',
    '    <div class="st-item" id="st-total"><span class="st-val">0</span><span class="st-label">Total</span></div>',
    '  </div>',
    '  <div id="tabs">',
    '    <div class="tab active" data-tab="chat">Chat</div>',
    '    <div class="tab" data-tab="log">Log</div>',
    '    <div class="tab" data-tab="live">Live</div>',
    '    <div class="tab" data-tab="explorer">Explorer</div>',
    '    <div class="tab" data-tab="ports">Ports</div>',
    '    <div class="tab" data-tab="git">Git</div>',
    '    <div class="tab" data-tab="pkgs">Pkgs</div>',
    '  </div>',
    '  <div id="panels">',
    '    <div class="panel active" id="panel-chat">',
    '      <div id="chat-msgs"><div class="msg buddy">👋 Hi! I\'m Buddy. Ask me anything.</div></div>',
    '      <div id="ai-expl" style="display:none; padding:10px;"></div>',
    '      <div id="chat-input-area">',
    '        <textarea id="chat-input" placeholder="Ask Buddy..." rows="1"></textarea>',
    '        <button id="send-btn" title="Send (Enter)">➤</button>',
    '      </div>',
    '    </div>',
    '    <div class="panel" id="panel-log">',
    '      <div class="log-filter-bar">',
    '        <input type="text" id="log-search" placeholder="Search logs...">',
    '        <button id="filter-toggle-btn" title="Toggle Filters">⚙️</button>',
    '        <div class="log-filters" id="log-filters-box">',
    '          <select id="term-filter" class="filter-select"><option value="all">All Terms</option></select>',
    '          <select id="status-filter" class="filter-select">',
    '            <option value="all">Status</option>',
    '            <option value="ok">Success</option>',
    '            <option value="warn">Warn</option>',
    '            <option value="err">Error</option>',
    '          </select>',
    '          <select id="project-filter" class="filter-select">',
    '            <option value="all">All Projects</option>',
    '          </select>',
    '          <select id="sort-filter" class="filter-select">',
    '            <option value="asc">Newest First</option>',
    '            <option value="desc">Oldest First</option>',
    '          </select>',
    '        </div>',
    '      </div>',
    '      <div class="scroll" id="log-list"><div class="empty"><div class="empty-icon">📋</div><div class="empty-text">No commands yet.</div></div></div>',
    '    </div>',
    '    <div class="panel" id="panel-live">',
    '      <div class="scroll" id="live-list">',
    '        <div class="empty"><div class="empty-icon">⚡</div><div class="empty-text">No active commands.</div></div>',
    '      </div>',
    '      <div id="terminal-selector" class="terminal-selector scroll"></div>',
    '    </div>',
    '    <div class="panel" id="panel-explorer">',
    '      <div class="ai-mover">',
    '        <input type="text" id="ai-mover-input" class="ai-mover-input" placeholder="AI Mover: e.g. \'go to components\'">',
    '      </div>',
    '      <div class="scroll" id="explorer-tree">',
    '        <div class="empty"><div class="empty-icon">📂</div><div class="empty-text">Loading workspace...</div></div>',
    '      </div>',
    '    </div>',
    '    <div class="panel" id="panel-ports"><div class="scroll" id="ports-list"><div class="empty"><div class="empty-icon">🔌</div><div class="empty-text">No dev servers detected.</div></div></div></div>',
    '    <div class="panel" id="panel-git"><div class="scroll" id="git-content"><div class="empty"><div class="empty-icon">🌿</div><div class="empty-text">No git repository.</div></div></div></div>',
    '    <div class="panel" id="panel-pkgs"><div class="scroll" id="pkgs-list"><div class="empty"><div class="empty-icon">📦</div><div class="empty-text">Scanning scripts...</div></div></div></div>',
    '  </div>',
    '  <div id="safety-overlay">',
    '    <div class="s-box">',
    '      <div class="s-icon">🛡️</div>',
    '      <div class="s-title">Dangerous Command</div>',
    '      <div id="safety-msg">This command might be destructive.</div>',
    '      <div id="safety-cmd-preview"></div>',
    '      <div class="s-btns">',
    '        <button id="s-cancel" class="s-btn">Cancel</button>',
    '        <button id="s-run" class="s-btn">Run Anyway</button>',
    '      </div>',
    '    </div>',
    '  </div>',
  ].join('\n');
}
